import Head from 'next/head'
import LandingPage from './landingPage'

export default function Home() {
  return (
    <div className="container-fluid">
      <Head>
        <title>Exponent Africa</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/expo.ico" />
        <link rel="preconnect" href="https://fonts.gstatic.com"/>
        <link href="https://fonts.googleapis.com/css2?family=Monda&display=swap" rel="stylesheet"/>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"/>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>     
      </Head>

      <main className="body">
        <LandingPage/>
        
      </main>

      <footer>

      </footer>
  
    </div>
  )
}
